#  CONFIG_SERIAL=y
# USART printf support (UART console backend for logging)
#  CONFIG_CONSOLE=y
#  CONFIG_UART_CONSOLE=y
CONFIG_LOG_BACKEND_UART=y
# ensure printk available
#  CONFIG_PRINTK=y

# Shell
CONFIG_SHELL_LOG_BACKEND=n

# ensure use nrf54l15 INTERNAL CLOCK
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
